"""
core.py - model, dataset, augmentation, loss, sampler and training-loop definitions.

Extracted verbatim from actionrec.ipynb (cells 13, 15, 17, 19, 21, 23, 25, 27) so that
train.py can reproduce the experiment without Jupyter. Do not edit this file by hand: if
the notebook changes, re-extract, otherwise the script and the notebook will drift apart.

CFG is bound at runtime by the caller (train.py sets core.CFG before use).
"""
import json
import math
import os
import random

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import Counter
from sklearn.metrics import (average_precision_score, roc_auc_score, f1_score,
                             precision_score, recall_score, precision_recall_curve,
                             precision_recall_fscore_support, mean_squared_error)
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import torchvision
from torchvision import transforms
from torchvision.models import mobilenet_v3_large, MobileNet_V3_Large_Weights

CFG = None  # bound by the caller

# Globals the notebook defined in surrounding cells and that the extracted code expects.
from tqdm.auto import tqdm
try:                                     # torch >= 2.0
    from torch.amp import autocast, GradScaler
except ImportError:                      # older torch
    from torch.cuda.amp import autocast, GradScaler
AMP_DEVICE_TYPE = "cuda" if torch.cuda.is_available() else "cpu"
AMP_ENABLED = torch.cuda.is_available()
g = torch.Generator()
g.manual_seed(42)


def set_seed(seed):
    """Seed python, numpy and torch, and re-seed the shared DataLoader generator."""
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    g.manual_seed(seed)

# ---------- notebook cell [13] ----------
def read_frames_with_count(path, num_frames, img_size, mode, stride=4, start=0):
    """
    Single-pass version: opens the video once, reads the frame count off the same handle,
    decides sampling indices, then decodes only the needed frames.
    """
    cap   = cv2.VideoCapture(path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    indices = sample_frame_indices(total, num_frames, mode=mode, stride=stride, start=start)

    if total <= 0:
        cap.release()
        return [np.zeros((img_size, img_size, 3), dtype=np.uint8) for _ in indices], indices

    idx_set    = sorted(set(indices))
    idx_to_frame = {}
    max_idx    = max(idx_set)

    # Runtime fix: jump close to the first needed frame instead of decoding from frame 0.
    # This helps both random training clips and sliding-window evaluation, especially on long videos.
    if len(idx_set) > 0:
        first_idx = idx_set[0]
        cap.set(cv2.CAP_PROP_POS_FRAMES, first_idx)
        pos = first_idx
    else:
        pos = 0

    while pos <= max_idx:
        ret, frame = cap.read()
        if not ret:
            break
        if pos in idx_set:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (img_size, img_size), interpolation=cv2.INTER_AREA)
            idx_to_frame[pos] = frame
        pos += 1
    cap.release()

    if len(idx_to_frame) == 0:
        return [np.zeros((img_size, img_size, 3), dtype=np.uint8) for _ in indices], indices

    last_good = next(iter(idx_to_frame.values()))
    out = []
    for i in indices:
        if i in idx_to_frame:
            last_good = idx_to_frame[i]
        out.append(last_good)
    return out, indices

def sample_frame_indices(total_frames, num_frames, mode="random", stride=4, start=0):
    """
    mode='random'  -> training: random window + jitter
    mode='uniform' -> val/test: deterministic, evenly spaced
    mode='window'  -> deterministic sliding window at inference
    """
    if total_frames <= 0:
        return [0] * num_frames

    if mode == "window":
        return [min(start + i * stride, total_frames - 1) for i in range(num_frames)]

    if mode == "uniform":
        if total_frames <= num_frames:
            return list(range(total_frames)) + [total_frames - 1] * (num_frames - total_frames)
        return np.linspace(0, total_frames - 1, num_frames).astype(int).tolist()

    # mode == 'random' (training)
    needed_span = num_frames * stride if stride else num_frames * 4
    if total_frames <= needed_span:
        return sorted(np.random.choice(total_frames, num_frames, replace=True).tolist())
    max_start  = total_frames - needed_span
    rnd_start  = random.randint(0, max_start)
    eff_stride = stride if stride else max(1, needed_span // num_frames)
    idxs = [min(rnd_start + i * eff_stride + random.randint(-1, 1), total_frames - 1)
            for i in range(num_frames)]
    return sorted([max(0, i) for i in idxs])


# ---------- notebook cell [15] ----------
class ClipAugmenter:
    """Applies the same spatial transform across every frame of a clip (train only)."""

    def __init__(self, img_size, mean, std, train=True):
        self.img_size = img_size
        self.mean  = np.array(mean, dtype=np.float32)
        self.std   = np.array(std,  dtype=np.float32)
        self.train = train

    def _get_train_params(self, h, w):
        """
        Draw ALL random parameters ONCE per clip.
        Crop offsets (top/left) are included here so every frame in the clip
        receives the same crop window — fixing the per-frame jitter bug in v1.
        """
        crop_scale = random.uniform(0.85, 1.0)
        ch = int(h * crop_scale)
        cw = int(w * crop_scale)
        top  = random.randint(0, max(h - ch, 0))
        left = random.randint(0, max(w - cw, 0))
        return dict(
            flip       = random.random() < 0.5,
            jitter     = random.random() < 0.5,
            blur       = random.random() < 0.2,
            brightness = random.uniform(0.8, 1.2),
            contrast   = random.uniform(0.8, 1.2),
            saturation = random.uniform(0.8, 1.2),
            crop_scale = crop_scale,
            crop_top   = top,
            crop_left  = left,
            crop_h     = ch,
            crop_w     = cw,
        )

    def _apply_to_frame(self, frame, params):
        if params["crop_scale"] < 1.0:
            t, l = params["crop_top"], params["crop_left"]
            ch,  cw = params["crop_h"], params["crop_w"]
            frame = frame[t:t+ch, l:l+cw]
            frame = cv2.resize(frame, (self.img_size, self.img_size), interpolation=cv2.INTER_AREA)

        if params["flip"]:
            frame = cv2.flip(frame, 1)

        if params["jitter"]:
            img  = frame.astype(np.float32)
            img *= params["brightness"]
            mean_pix = img.mean(axis=(0, 1), keepdims=True)
            img  = (img - mean_pix) * params["contrast"] + mean_pix
            gray = img.mean(axis=2, keepdims=True)
            img  = (img - gray) * params["saturation"] + gray
            frame = np.clip(img, 0, 255).astype(np.uint8)

        if params["blur"]:
            frame = cv2.GaussianBlur(frame, (3, 3), 0)

        return frame

    def __call__(self, frames):
        # Draw params once using the first frame's dimensions
        h, w, _ = frames[0].shape
        params = self._get_train_params(h, w) if self.train else {}
        out = []
        for f in frames:
            if self.train:
                f = self._apply_to_frame(f, params)
            f = f.astype(np.float32) / 255.0
            f = (f - self.mean) / self.std
            out.append(f.transpose(2, 0, 1))   # HWC → CHW
        clip = np.stack(out, axis=0)            # [T, C, H, W]
        return torch.from_numpy(clip).float()


# ---------- notebook cell [17] ----------
def seed_worker(worker_id):
    """
    Ensures DataLoader workers produce deterministic results across runs.

    fix: also disables OpenCV's internal thread pool inside each worker process.
    Without this, every one of the `num_workers` processes spawns its own OpenCV
    thread pool on top of PyTorch's own multiprocessing workers, oversubscribing
    CPU cores and causing severe (sometimes near-hanging) slowdowns when decoding
    video with cv2.VideoCapture inside Dataset.__getitem__ — a well-known issue
    combining OpenCV + multiprocess DataLoaders, including on Kaggle.
    """
    cv2.setNumThreads(0)
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

g = torch.Generator()

class UCFCrimeClipDataset(Dataset):
    def __init__(self, records, cfg, train=True, motion_scores=None):
        self.records     = records
        self.cfg         = cfg
        self.train       = train
        self.augmenter   = ClipAugmenter(cfg.IMG_SIZE, cfg.MEAN, cfg.STD, train=train)
        self.motion_scores = motion_scores or {}

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        rec          = self.records[idx]
        path, label  = rec["path"], rec["label"]
        mode         = "random" if self.train else "uniform"
        frames, _idx = read_frames_with_count(
            path, self.cfg.NUM_FRAMES, self.cfg.IMG_SIZE,
            mode=mode, stride=self.cfg.INFER_STRIDE,
        )
        clip = self.augmenter(frames)   # [T, C, H, W]
        return clip, torch.tensor(label, dtype=torch.float32), path

# ── Background-subtraction hard-negative mining ─────────────────────────────
def estimate_motion_score_mog2(path, num_probe_frames=10):
    """
    MOG2 background subtractor — more robust than frame-differencing.
    Frame differencing conflates camera shake, lighting flicker, and rain with
    genuine foreground motion.  MOG2 explicitly models the background distribution
    and outputs a foreground mask, making it less sensitive to those artefacts.

    Returns mean foreground pixel fraction across sampled frames (higher = more motion).
    """
    cap   = cv2.VideoCapture(path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total < 2:
        cap.release()
        return 0.0

    mog2   = cv2.createBackgroundSubtractorMOG2(detectShadows=False)
    idxs   = np.linspace(0, total - 1, num_probe_frames).astype(int)
    scores = []
    pos    = 0
    idx_set = set(idxs.tolist())
    while pos <= idxs[-1]:
        ret, frame = cap.read()
        if not ret:
            break
        if pos in idx_set:
            small = cv2.resize(frame, (64, 64))
            mask  = mog2.apply(small)
            scores.append(mask.mean() / 255.0)   # fraction of pixels marked foreground
        pos += 1
    cap.release()
    return float(np.mean(scores)) if scores else 0.0

def load_motion_cache(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}

def save_motion_cache(cache, path):
    with open(path, "w") as f:
        json.dump(cache, f)

def build_class_balanced_sampler(records, cfg, hard_negative_topk_frac=0.15, motion_cache=None):
    """
    Two-level balanced sampler.

    Fixes a data-imbalance issue without changing the task from binary classification:
      1) keeps the epoch roughly balanced as Normal vs Suspicious;
      2) spreads the Suspicious half across Burglary, Fighting, and Stealing so the
         smaller Fighting class is not under-sampled;
      3) still upweights high-motion Normal videos as hard negatives.
    """
    class_names = np.array([r.get("class_name", "Unknown") for r in records])
    labels      = np.array([r["label"] for r in records])

    suspicious_class_names = sorted({
        cls for cls, lab in zip(class_names, labels)
        if lab == 1 and cls != "Unknown"
    })

    weights = np.zeros(len(records), dtype=np.float64)

    # Reserve half the sampling probability mass for Normal and half for Suspicious.
    normal_idxs = np.where(labels == 0)[0]
    if len(normal_idxs) > 0:
        weights[normal_idxs] = 0.5 / len(normal_idxs)

    # Share the Suspicious half equally across the suspicious subclasses.
    if len(suspicious_class_names) > 0:
        per_suspicious_class_mass = 0.5 / len(suspicious_class_names)
        for cls in suspicious_class_names:
            cls_idxs = np.where((labels == 1) & (class_names == cls))[0]
            if len(cls_idxs) > 0:
                weights[cls_idxs] = per_suspicious_class_mass / len(cls_idxs)

    # Fallback safety if a class name is missing or weights did not fill correctly.
    if not np.isfinite(weights).all() or weights.sum() <= 0:
        labels_list = labels.tolist()
        class_counts = Counter(labels_list)
        inv_freq = {c: 1.0 / class_counts[c] for c in class_counts}
        weights = np.array([inv_freq[l] for l in labels], dtype=np.float64)

    motion_cache = motion_cache or {}

    # Hard-negative mining: only high-motion Normal videos receive an extra boost.
    if len(normal_idxs) > 0 and hard_negative_topk_frac > 0:
        scores = []
        for i in normal_idxs:
            p = records[i]["path"]
            if p not in motion_cache:
                motion_cache[p] = estimate_motion_score_mog2(p)
            scores.append(motion_cache[p])

        scores = np.array(scores)
        k = max(1, int(len(scores) * hard_negative_topk_frac))
        hard_global_idx = normal_idxs[np.argsort(scores)[-k:]]
        weights[hard_global_idx] *= 1.5   # moderate boost; avoids overwhelming rare suspicious clips

    # Normalize after hard-negative boost.
    weights = weights / weights.sum()

    samples_per_video = int(getattr(cfg, "TRAIN_SAMPLES_PER_VIDEO", 1))
    sampler = WeightedRandomSampler(
        weights=torch.from_numpy(weights),
        num_samples=len(weights) * max(1, samples_per_video),
        replacement=True,
    )

    # Lightweight audit so the user can see what the sampler is doing.
    print("Sampler class counts:", Counter(class_names.tolist()))
    expected_class_draws = {}
    for cls in sorted(set(class_names.tolist())):
        cls_mass = float(weights[class_names == cls].sum())
        expected_class_draws[cls] = round(cls_mass * len(weights) * max(1, samples_per_video), 1)
    print("Expected sampled clips/epoch by class:", expected_class_draws)

    return sampler, motion_cache

# ── Fix: drop_last only on train loader; eval loaders use full dataset ───────
# drop_last=True is kept for train because replacement sampling and BatchNorm are more stable
# with full batches. Val/test can safely use drop_last=False because TSM only requires
# each sample to contain CFG.NUM_FRAMES frames; it does not require a fixed batch size.
def make_eval_loader(dataset, cfg):
    """Evaluation loader: keeps the final partial batch; no samples are discarded."""
    return DataLoader(
        dataset,
        batch_size=cfg.BATCH_SIZE,
        shuffle=False,
        num_workers=cfg.NUM_WORKERS,
        pin_memory=True,
        drop_last=False,
        worker_init_fn=seed_worker,
        generator=g,
        persistent_workers=(cfg.NUM_WORKERS > 0),
    )


# ---------- notebook cell [19] ----------
class TemporalShift(nn.Module):
    """
    TSM channel-shift operation.
    Input shape during shift: [N*T, C, H, W] → reshaped to [N, T, C, H, W],
    a portion of channels is shifted +1 step, another -1 step, rest unchanged.
    """
    def __init__(self, num_frames, shift_div=8):
        super().__init__()
        self.num_frames = num_frames
        self.shift_div  = shift_div

    def forward(self, x):
        nt, c, h, w = x.size()
        if nt % self.num_frames != 0:
            raise RuntimeError(
                f"TemporalShift got {nt} frame-tensors, not divisible by "
                f"num_frames={self.num_frames}.  Use drop_last=True on train loader."
            )
        n_batch = nt // self.num_frames
        x   = x.view(n_batch, self.num_frames, c, h, w)
        fold = c // self.shift_div
        out = torch.zeros_like(x)
        out[:, :-1, :fold]          = x[:, 1:, :fold]
        out[:, 1:,  fold:2*fold]    = x[:, :-1, fold:2*fold]
        out[:, :,   2*fold:]        = x[:, :,   2*fold:]
        return out.view(nt, c, h, w)

class TSMBlockWrapper(nn.Module):
    """Wraps an existing conv block so TSM is applied right before it."""
    def __init__(self, block, num_frames, shift_div=8):
        super().__init__()
        self.shift = TemporalShift(num_frames, shift_div)
        self.block = block

    def forward(self, x):
        return self.block(self.shift(x))

def insert_tsm_into_mobilenetv3(backbone, num_frames, shift_div=8, every_n_blocks=1):
    """
    Wraps every Nth inverted-residual block of MobileNetV3's feature extractor with TSM.
    every_n_blocks=1    → shift before every block (standard TSM).
    every_n_blocks=2    → lighter profile; see ablation study in Section 5a.
    every_n_blocks=None → no TSM wrapper; still processes all T frames and temporal-averages.
    """
    if every_n_blocks is None or every_n_blocks <= 0:
        return backbone

    features = backbone.features
    count = 0
    for i, layer in enumerate(features):
        if i == 0:
            continue    # skip the stem conv
        count += 1
        if count % every_n_blocks == 0:
            features[i] = TSMBlockWrapper(layer, num_frames, shift_div)
    return backbone

class SuspiciousActivityModel(nn.Module):
    """
    MobileNetV3-Large → TSM → Global Average Pooling → Dropout → Linear → Binary Logit
    (Model A from the design spec)
    """
    def __init__(self, num_frames=8, dropout=0.3, pretrained=True,
                 shift_div=8, every_n_blocks=1):
        super().__init__()
        self.num_frames = num_frames
        # Use ImageNet weights when available. On Kaggle, downloading pretrained
        # weights can fail if internet is disabled; this fallback prevents the notebook
        # from crashing and clearly tells you when training starts from random weights.
        weights = None
        if pretrained:
            try:
                weights = torchvision.models.MobileNet_V3_Large_Weights.IMAGENET1K_V1
                backbone = torchvision.models.mobilenet_v3_large(weights=weights)
            except Exception as e:
                print("[WARN] Could not load/download MobileNetV3-Large pretrained weights.")
                print("       Falling back to random initialization. Reason:", repr(e))
                backbone = torchvision.models.mobilenet_v3_large(weights=None)
        else:
            backbone = torchvision.models.mobilenet_v3_large(weights=None)

        backbone = insert_tsm_into_mobilenetv3(backbone, num_frames, shift_div, every_n_blocks)
        self.features = backbone.features
        self.gap      = nn.AdaptiveAvgPool2d(1)
        feat_dim      = backbone.classifier[0].in_features   # 960 for MobileNetV3-Large
        self.dropout  = nn.Dropout(dropout)
        self.fc       = nn.Linear(feat_dim, 1)

    def forward(self, x):
        n, t, c, h, w = x.shape
        assert t == self.num_frames, f"Expected {self.num_frames} frames, got {t}"
        x     = x.view(n * t, c, h, w)
        feats = self.features(x)
        feats = self.gap(feats).flatten(1)
        feats = feats.view(n, t, -1).mean(dim=1)   # temporal avg pool → [N, C']
        feats = self.dropout(feats)
        return self.fc(feats).squeeze(1)            # [N]

# ---------- notebook cell [21] ----------
class FocalLoss(nn.Module):
    """Binary focal loss.  alpha upweights the positive (suspicious) class."""
    def __init__(self, alpha=0.75, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        bce      = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
        probs    = torch.sigmoid(logits)
        p_t      = probs * targets + (1 - probs) * (1 - targets)
        alpha_t  = self.alpha * targets + (1 - self.alpha) * (1 - targets)
        loss     = alpha_t * (1 - p_t).pow(self.gamma) * bce
        return loss.mean()

# ---------- notebook cell [23] ----------
def compute_metrics(y_true, y_prob, threshold=0.5):
    y_true = np.asarray(y_true)
    y_prob = np.asarray(y_prob)
    y_pred = (y_prob >= threshold).astype(int)

    pr_auc = average_precision_score(y_true, y_prob)
    try:
        roc_auc = roc_auc_score(y_true, y_prob)
    except ValueError:
        roc_auc = float("nan")

    # fix: added RMSE/MSE. Note these are computed between the raw probability y_prob
    # and the binary label y_true (0/1), NOT between y_pred and y_true -- squared error
    # against a hard 0/1 prediction collapses to the same information as accuracy and
    # is not a standard reporting choice. MSE-of-probability-vs-binary-label is formally
    # the Brier score, a real and standard metric for probabilistic binary classifiers
    # (lower is better; measures both calibration and discrimination jointly). RMSE is
    # just its square root, included only for direct comparability since it was
    # specifically requested -- it does not carry additional information beyond MSE
    # for this use case, and neither metric should be read the way RMSE/MSE are read for
    # a continuous regression target (e.g. there is no natural "units" interpretation,
    # since the target is categorical not continuous).
    mse  = float(np.mean((y_prob - y_true) ** 2))
    rmse = float(np.sqrt(mse))

    return {
        "pr_auc":    pr_auc,
        "roc_auc":   roc_auc,
        "f1":        f1_score(y_true,        y_pred, zero_division=0),
        "recall":    recall_score(y_true,    y_pred, zero_division=0),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "mse":       mse,
        "rmse":      rmse,
    }

def best_threshold_for_f1(y_true, y_prob):
    """Grid search over thresholds maximising F1 on the validation set."""
    precisions, recalls, thresholds = precision_recall_curve(y_true, y_prob)
    f1s = 2 * precisions * recalls / np.clip(precisions + recalls, 1e-8, None)
    best_idx   = np.nanargmax(f1s[:-1]) if len(f1s) > 1 else 0
    best_thresh = thresholds[best_idx] if len(thresholds) > 0 else 0.5
    return float(best_thresh), float(f1s[best_idx])


# ---------- notebook cell [25] ----------
class CheckpointManager:
    """Tracks and saves latest / best-PR-AUC / best-ROC-AUC model states."""
    def __init__(self, output_dir, cfg):
        self.output_dir  = output_dir
        self.cfg         = cfg
        self.best_pr_auc  = -1.0
        self.best_roc_auc = -1.0
        os.makedirs(output_dir, exist_ok=True)

    def _save(self, filename, model, optimizer, epoch, metrics, scheduler=None, scaler=None):
        path = os.path.join(self.output_dir, filename)
        # fix: scheduler and scaler state are now saved alongside model/optimizer.
        # ReduceLROnPlateau tracks patience/cooldown/best internally via its own state_dict,
        # and GradScaler tracks its dynamic loss-scale factor via its own state_dict. Neither
        # was being persisted before, so resuming from a checkpoint silently reset the LR
        # scheduler's patience counter and the AMP scaler's loss scale to their initial values
        # instead of continuing from where training actually left off.
        torch.save({
            "epoch": epoch,
            "model_state": model.state_dict(),
            "optimizer_state": optimizer.state_dict(),
            "scheduler_state": scheduler.state_dict() if scheduler is not None else None,
            "scaler_state": scaler.state_dict() if scaler is not None else None,
            "metrics": metrics,
        }, path)
        return path

    def update(self, model, optimizer, epoch, val_metrics, scheduler=None, scaler=None):
        improved_pr = False
        self._save(self.cfg.SAVE_LATEST, model, optimizer, epoch, val_metrics, scheduler, scaler)
        if val_metrics["pr_auc"] > self.best_pr_auc:
            self.best_pr_auc = val_metrics["pr_auc"]
            self._save(self.cfg.SAVE_BEST_PRAUC, model, optimizer, epoch, val_metrics, scheduler, scaler)
            improved_pr = True
            print(f"  -> New best PR-AUC: {self.best_pr_auc:.4f}  (saved {self.cfg.SAVE_BEST_PRAUC})")
        if not math.isnan(val_metrics["roc_auc"]) and val_metrics["roc_auc"] > self.best_roc_auc:
            self.best_roc_auc = val_metrics["roc_auc"]
            self._save(self.cfg.SAVE_BEST_ROCAUC, model, optimizer, epoch, val_metrics, scheduler, scaler)
            print(f"  -> New best ROC-AUC: {self.best_roc_auc:.4f}  (saved {self.cfg.SAVE_BEST_ROCAUC})")
        return improved_pr

# ---------- notebook cell [27] ----------
def run_epoch(model, loader, optimizer, criterion, device, scaler, train=True, desc=None):
    model.train() if train else model.eval()
    total_loss    = 0.0
    n_samples     = 0
    all_targets, all_probs = [], []

    # fix: inference_mode is faster/lower-memory than no_grad for the eval path;
    # set_grad_enabled is still required for the train path since it needs autograd.
    grad_ctx = torch.enable_grad() if train else torch.inference_mode()
    # fix: a tqdm progress bar with live loss is added so long epochs (on-the-fly video
    # decoding can make a single epoch take many minutes) show visible progress on Kaggle
    # instead of appearing to hang silently.
    pbar = tqdm(loader, desc=desc or ("train" if train else "val"), leave=False)
    with grad_ctx:
        for clips, labels, _paths in pbar:
            clips  = clips.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            if train:
                optimizer.zero_grad(set_to_none=True)   # fix: avoids zeroing grad tensors, saves memory/time

            # Mixed-precision forward pass (no-op on CPU / if AMP disabled)
            with autocast(AMP_DEVICE_TYPE, enabled=AMP_ENABLED):
                logits = model(clips)
                loss   = criterion(logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
                scaler.step(optimizer)
                scaler.update()

            bs = clips.size(0)
            total_loss += loss.item() * bs
            n_samples  += bs
            probs = torch.sigmoid(logits).detach().cpu().float().numpy()
            all_probs.extend(probs.tolist())
            all_targets.extend(labels.detach().cpu().numpy().tolist())
            pbar.set_postfix(loss=f"{loss.item():.4f}")

    avg_loss = total_loss / max(n_samples, 1)
    # Use tuned threshold=0.5 during training loop only for monitoring;
    # the real decision threshold is selected on the validation set after training.
    metrics = compute_metrics(all_targets, all_probs, threshold=0.5)
    metrics["loss"] = avg_loss
    return metrics
